package com.evan.euler;
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class ProblemTwo {

	public static void main(String args[]) {
		int answer = 0;
		
		answer = ProblemTwo();
		
		System.out.println(answer);
	}
	
	public static int ProblemTwo(){
		int sum = 0;
		int tertiary = 0;
		int first = 1;
		int second = 2;
				
		
		
		while (second<4000000) {
			if (second%2==0) {
				sum += second;
			}
			tertiary = first;
			first = second;
			second += tertiary;
			
		}
		
		return sum;
	}
	
	
}
