package com.evan.euler;

import java.util.ArrayList;
import java.util.List;

/*The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
 */

public class ProjectTwelve extends MathFunctions{

	public static void main(String args[]) {
		long answer = 0;
		
		answer = ProblemTwelve();
		
		System.out.println(answer);
	}

	private static long ProblemTwelve() {
		
		List<Integer> list = new ArrayList<Integer>();
		int itemCount = 0;
		int triangleSum = 0;
		
		for (int i=1; itemCount<=500; i++){
		triangleSum += i;
		list = factorsOfNumber(triangleSum);
		itemCount = list.size();
		
		}
		return triangleSum;
	}
}
