package main.java.problems;

import main.java.main.Problem;
import  main.java.main.annotations.Solved;

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

@Solved
public class _002 extends Problem {

    public static void main(String[] args) {

        Problem p = new _002();
        p.run();

        p.printAnswer();
        System.out.println(p.answer());

    }

    public void run() {
        int sum = 0;
        int tertiary = 0;
        int first = 1;
        int second = 2;



        while (second < 4000000) {
            if (second % 2 == 0) {
                sum += second;
            }
            tertiary = first;
            first = second;
            second += tertiary;

        }
        this.answer = sum;
    }
}
